language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - echo 'America/Los_Angeles' | sudo tee /etc/timezone
script:
  - python -m pgesmd.test_helpers
  - python -m pgesmd.test_api