language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - export TZ=America/Los_Angeles
script:
  - python -m pgesmd.test_helpers
  - python -m pgesmd.test_api