language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
before_script:
  - export TZ=America/Los_Angeles
  - export FLASK_APP=pgesmd
  - export FLASK_ENV=development
  - export SECRET_KEY=dev
  - export JWT_SECRET_KEY=dev
  - export JWT_BLACKLIST_ENABLED=True
  - export JWT_TOKEN_LOCATION=cookies
  - export JWT_ACCESS_COOKIE_PATH=/api/
  - export JWT_REFRESH_COOKIE_PATH=/token/refresh
  - export JWT_COOKIE_CSRF_PROTECT=True
  - export PROD_JWT_COOKIE_SECURE=True
  - export DEV_JWT_COOKIE_SECURE=False
  - export PROD_DATABASE_URI=sqlite:///../data/energy_history.db
  - export DEV_DATABASE_URI=sqlite:///../test/data/energy_history_test.db
script:
  