#!/bin/bash
source venv/bin/activate
export FLASK_APP=open_energy_view
export FLASK_ENV=production
export SECRET_KEY=dev
export JWT_SECRET_KEY=dev
export JWT_BLACKLIST_ENABLED=True
export JWT_TOKEN_LOCATION=cookies
export JWT_ACCESS_COOKIE_PATH=/api/
export JWT_REFRESH_COOKIE_PATH=/token/refresh
export JWT_COOKIE_CSRF_PROTECT=True
export PROD_JWT_COOKIE_SECURE=True
export DEV_JWT_COOKIE_SECURE=False
export PROD_DATABASE_URI=sqlite:///../test/data/energy_history_test.db
export DEV_DATABASE_URI=sqlite:///../test/data/energy_history_test.db
flask run --host='0.0.0.0'
